# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGopherCli < Formula
  desc "A tool to get gopher image!"
  homepage "https://goreleaser.com/borischen0203/go-gopher-cli"
  version "1.1.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.6/go-gopher-cli_1.1.6_macOS-64bit.tar.gz"
      sha256 "7f1e077a32c27795099b891a6de93461e292e371ebfaf78eee0cae75452c52e8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.6/go-gopher-cli_1.1.6_macOS-ARM64.tar.gz"
      sha256 "39a441a537e5c964438d2dfbb409a130ee2f048508649e746ecfdaf4f3fc1084"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.6/go-gopher-cli_1.1.6_Linux-64bit.tar.gz"
      sha256 "9437b9aae7c5fcf5cf09844deacdcac61aac5ebd48c8f721f365c5fa9024760f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.6/go-gopher-cli_1.1.6_Linux-ARM64.tar.gz"
      sha256 "4955dea5e6fcad899f70486023a95050572fcfe52b4a0bc0704a2df30dec2a4f"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "go-gopher-cli"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
