# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGopherCli < Formula
  desc "A tool to get gopher image!"
  homepage "https://goreleaser.com/borischen0203/go-gopher-cli"
  version "1.1.4"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.4/go-gopher-cli_1.1.4_macOS-64bit.tar.gz"
      sha256 "d206ef253538704b0f60503f1aa239e7d5501d75173672a1c8845bd4ec3de5eb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.4/go-gopher-cli_1.1.4_macOS-ARM64.tar.gz"
      sha256 "deff9a816bde743fa8c8ac5a15111ff0938262654a75e2b543fb6d1cf6bb1146"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.4/go-gopher-cli_1.1.4_Linux-64bit.tar.gz"
      sha256 "6ba0da8a4d858a73235e2dfaf666a059a9d04989bba587dc1c82931ab04d1bdc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.4/go-gopher-cli_1.1.4_Linux-ARM64.tar.gz"
      sha256 "1af9bb38a5e751a0c92fa4d5f7c7fab1268bf34702c32973113fca7ba94a51cf"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "goreleaser"
    bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
    fish_completion.install "completions/goreleaser.fish"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
